### PR TITLE
Feature/add link

### PR DESCRIPTION
**Pull request by proudynyu**
#### What problem is this solving?

Some stores uses the `clusterHighlight` to show some kind o flag to indicate a collection where that product belongs and, it have a link to that collection based on the **cluster ID**.
With that in mind, we on ACCT have thought first on a custom component to create this link and, with a little more tought, we conclude that would do more good to add on the VTEX component.

#### How to test it?

This could be test using this branch and link it with the new props on the `product-hightlight-text`.
I also have a workspace that I'm using for test:

[Link to Workspace](https://igor2--iocea.myvtex.com/bermuda-jeans-de-moletom-masculina-slim-com-cordao-azul-claro-9941835-azul_claro/p)

#### Screenshots or example usage:

`block`:

image

`structure (DevTools img)`: 

image

`PDP (this is using some CSS, but the cluster is the Green Flag)`:

image

#### Describe alternatives you've considered, if any.

One alternative would be the inside team o VTEX to analyze if is possible to implment this idea, this would help a lot 🥇 
I also accept any suggestion to change the structure that I have created for this PR 🚀 

_ps: I did not change the CHANGELOG because I think this is with VTEX team right?_

### CODE REVIEW

**Comment by proudynyu** [comment]
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch (backwards-compatible bug fixes)
> * [x]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

**Review by victorhmp — APPROVED** [review]
LGTM! Thanks for the contribution!

About the CHANGELOG, you can change it, it makes it easier for us to merge the PR :) Just follow the pattern used in the previous entries and it should be fine. You just need to place your change's description below the `Unreleased` header, then a bot will tag the correct version once this is released.

Just one more thing, I'm going to add our technical writer to the reviewers, so that she can review the docs!

**Comment by proudynyu** [comment]
@victorhmp I have add the Changelog, I will be waiting for the others reviews to see if it need any correction 🚀

**Review by klzns — APPROVED** [review]

**Comment by klzns** [comment]
Thanks for contributing @proudynyu! I changed the solution a bit so it can be more flexible.

**Comment by klzns** [comment]
@allcontributors add @proudynyu for code

**Pull request merged**
